<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3devtools"
 *
 * Auto generated by Extension Builder 2019-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 development tools',
    'description' => 'TYPO3 development tools',
    'category' => 'misc',
    'author' => 'R3 H6',
    'author_email' => 'r3h6@outlook.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
